### PR TITLE
Unix support

### PR DESCRIPTION
**Pull request by CedricGuillemet**
Unix support for task scheduler

### CODE REVIEW

**Comment by ryantrem** [comment]
@syntheticmagus - it would be nice if we could have something like a `PlatformDefault` directory alongside Android, iOS, etc., and use files from that directory when we don't have platform specific implementations. Is this possible/easy with cmakelists.txt?

**Comment by bghgary** [comment]
@ryantrem CMakeLists.txt can certainly do this, but I don't know if it makes sense here. The current stopgap solution for `threadpool_scheduler` is a placeholder and I'm sure it should be used as the official fallback behavior.

**Comment by ryantrem** [comment]
@bghgary yea that's true, though I don't think the idea of having special platform specific implementations is abnormal. We can wait until we have a more "real" case of that though, it just seems like a hassle to have to do these kinds of updates when trying to use Arcana on a new platform.

**Comment by bghgary** [comment]
I don't know. My opinion is that if we have platform specific code, we would rather know about what platforms are missing.

**Comment by bghgary** [comment]
I've updated the title in #8 to reflect the new platform.

**Pull request merged**
